version: ''

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: boss
      POSTGRES_DB: pay_service_db
    ports:
      - '5433:5433'
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
volumes:
  pg_data: