[app_settings]
app_port='8000'
app_version='1.0.0'
app_name='pay_service'
app_host='127.0.0.1'
app_mount='/api/v1'

[db_settings]
db_name='pay_service_db'
db_user='postgres'
db_password='pass'
db_host='localhost'
db_port='5433'